# Generated by Django 3.2.4 on 2021-07-30 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0012_auto_20210730_1013'),
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bought_items',
            name='ebook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='library.ebook'),
            preserve_default=False,
        ),
    ]
