# Generated by Django 3.2.4 on 2021-07-31 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0013_auto_20210731_0959'),
        ('entities', '0002_bought_items_ebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='bought_items',
            name='library',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='library.library'),
            preserve_default=False,
        ),
    ]
