# Generated by Django 3.2.4 on 2022-01-15 11:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_bought_items_library'),
    ]

    operations = [
        migrations.CreateModel(
            name='paypal_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
